version: "3.8"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    command: >
      bash -c "poetry run alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
